version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mydump2bq_mysql
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./:/work
    environment:
      MYSQL_USER: example
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example

  mysqldump:
    image: mysql
    container_name: mydump2bq_mysqldump
    links:
      - mysql
    volumes:
      - /var/tmp/your-app/mysql:/var/lib/mysql
      - ./:/work
    command: tail -f /dev/null

  golang:
    image: golang
    container_name: mydump2bq_golang
    links:
      - mysql
    volumes:
      - ./:/work
    command: tail -f /dev/null
